### ISSUE TITLE
Test oppkobling mellom API og react

### ISSUE THREAD

**Issue by Bjorgeh** [Bjorgeh/rapportsystem-frontend#14]

**Comment by Anzure** [comment]
Litt uklart hvordan man skal autentisere seg mot backend API-et.

**Comment by Bjorgeh** [comment]
Det er forståelig, jeg foreslår at vi benytter oss av JWT tokens istede for sessions hvis det blir for ugunstig siden backend og frontend er standalones.  Jeg må skrive om litt i APIet, men da vil o
ppkobling mellom react og API se omtrent slik ut:

import React, { useState, useEffect } from 'react';
import axios from 'axios';

const API_URL = 'http://localhost:5000'; // Endre dette til din Flask API URL

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (token) {
      setIsAuthenticated(true);
    }
  }, []);

  const login = async (username, password) => {
    try {
      const response = await axios.post(`${API_URL}/login`, { username, password });
      localStorage.setItem('token', response.data.access_token);
      setIsAuthenticated(true);
    } catch (error) {
      console.error('Login failed:', error);
      // Håndter feil (f.eks. vis en feilmelding)
    }
  };

  const fetchProtectedData = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`${API_URL}/protected`, {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      console.log('Protected data:', response.data);
      // Håndter beskyttede data her
    } catch (error) {
      console.error('Error fetching protected data:', error);
      // Håndter feil (f.eks. omdiriger til innlogging)
    }
  };

  return (
    <div>
      {isAuthenticated ? (
        <div>
          <p>Du er logget inn</p>
          <button onClick={fetchProtectedData}>Hent Beskyttede Data</button>
        </div>
      ) : (
        <div>
          <button onClick={() => login('brukernavn', 'passord')}>Logg Inn</button>
        </div>
      )}
    </div>
  );
}

export default App;

**Comment by Bjorgeh** [comment]
Deler hele samtalen med kompis her:
https://chat.openai.com/share/79ee06ad-984e-411e-b409-e203c4f554a6

**Comment by Anzure** [comment]
@Bjorgeh Det høres ut som en god løsning med JWT tokens. Vil foreslår å skrive litt om da, har brukt JWT tokens tidligere og det fungerte knall - det var med Java backend og React frontend da. Om du får det til i flask, er det nice 😃

**Comment by Bjorgeh** [comment]
Dette er vell gjort? Kan vi lukke denne? @anzure

**Comment by Bjorgeh** [comment]
Lukker denne da oppkobling er testet og registrert oppegående.
