### ISSUE TITLE
Avgjøre program for utvikling av web interface ( avgjort = React, Flask, MySql)

### ISSUE THREAD

**Issue by plankeP** [Bjorgeh/rapportsystem-frontend#3]

**Comment by rudabrah** [comment]
Vi har valgt å kjøre React front-end. Eget repo for dette. Videre kjører vi Python-flask backend med MySQL som database. Disse har også egne repoer

**Comment by Bjorgeh** [comment]
Front-end kan lages direkte i rapportsystem repo, kan bytte navn til front-end på det om så. Backend med python og MySQL blir i back-end repo 💃
