### ISSUE TITLE
Get values from API for frontpage graph

### ISSUE THREAD

**Issue by rudabrah** [Bjorgeh/rapportsystem-frontend#35]
Retrieve report values from backend API and load into diagram/graph in frontpage/dashboard/overview ([index.js](https://github.com/Bjorgeh/rapportsystem-frontend/blob/main/src/pages/index.js)) page.

### Get values by report count
URL: `/api/user/post/extractPreciseData`
Method: POST
Example body:
```json
{
  "table_name": "BorreproveRapport",
  "date_start": "1992-01-01",
  "date_stop": "2025-01-31"
}
```
### Get values by date range
URL: `/api/user/post/extractPreciseData`
Method: POST
Example body:
```json
{
  "table_name": "BorreproveRapport",
  "rapport_count": "5"
}
```

### Example response body
```json
{
  "requested_data": {
    "BorreproveRapport": {
      "Data": [
        {
          "id": 1,
          "part_type": "Type1",
          "stove": "Stove1",
          "catalog_number": 391,
          "test_amount": 1,
          "ordrer_number": "Order87",
          "approved": 0,
          "date": "2024-03-26",
          "time": "17:06:08",
          "sign": "Name91"
        },
        {
          "id": 2,
          "part_type": "Type21",
          "stove": "Stove2",
          "catalog_number": 638,
          "test_amount": 5,
          "ordrer_number": "Order43",
          "approved": 1,
          "date": "2024-03-26",
          "time": "17:06:08",
          "sign": "Name26"
        }
      ]
    }
  }
}
```

**Comment by Anzure** [comment]
[🎉 Introduced functional graph from API.](https://github.com/Bjorgeh/rapportsystem-frontend/commit/bbc30d0a62d61ce03229ed9b4246eea3ec876ab8)
Load diagram data from Backend API and show visual graph, and more!

[📋 Improved documentation and more!](https://github.com/Bjorgeh/rapportsystem-frontend/commit/dd7e48ff9b86666b60f84f4c405d4ecfd9722185) 
Hopefully also fixed CRLF and lint warnings.

![image](https://github.com/Bjorgeh/rapportsystem-frontend/assets/9752808/f12fd6bb-433a-43e2-9f07-a78669d269dd)

Ready for testing and QA. Opening pull request for code review now... 😄
