### ISSUE TITLE
milestone 4 - Skrive ferdig Skriftlig forprosjektleveranse

### ISSUE THREAD

**Issue by plankeP** [Bjorgeh/rapportsystem-frontend#5]

**Comment by rudabrah** [comment]
Kommet ganske godt i gang. Det eneste som gjenstår nå er å få inn risker, mitigasjon av risker, og korrigere så overskrifter osv. fungerer. Det må også legges inn kildehenvisninger.

**Comment by rudabrah** [comment]
Ferdig
